version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mydb
    ports:
      - "3308:3308"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: mysql
      PMA_USER: user
      PMA_PASSWORD: password
      PMA_DATABASE: mydb
    ports:
      - "8081:80"
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
